# Makefile zur Erstellung der Enhanced GEM-Library mit m68k-atari-mint-gcc
# Builds with 32-bit int (no -mshort) using modern gemlib (gem.h)

CC = m68k-atari-mint-gcc
AR = m68k-atari-mint-ar
RM = rm -f

# Name der erzeugten Library-Datei
LIB_NAME = libe_gem.a

# GCC Compiler Optionen
GCCOPTS = -O2 -fomit-frame-pointer -fno-strict-aliasing

CFLAGS = -Wall $(GCCOPTS) \
         -Wno-incompatible-pointer-types -Wno-int-conversion \
         -Wno-pointer-to-int-cast \
         -Wno-implicit-function-declaration \
         -D__CREATE_E_GEM_LIB__ -D__TCC_COMPAT__

OBJS = dial.o xacc_av.o objcedit.o objc.o popup.o graf.o tool.o \
       window.o event.o rc_ob_c.o fselect.o alerts.o dragdrop.o filetool.o

$(LIB_NAME): $(OBJS)
	$(AR) rcs $(LIB_NAME) $(OBJS)

$(OBJS): e_gem.h proto.h

.PHONY: clean cleanall

CLEANFILES = $(OBJS) compile.err *~
CLEANALLFILES = $(CLEANFILES) $(LIB_NAME)

clean:
	$(RM) $(CLEANFILES)

cleanall:
	$(RM) $(CLEANALLFILES)
