# Makefile zur Erstellung der Enhanced GEM-Library mit dem GNU CC
# Variante OHNE -mshort: int ist 32 Bit (4 Byte)
# Die Library benutzt INT16 (typedef auf short) fuer alle AES/VDI-Daten.

CC = m68k-atari-mint-gcc
AR = m68k-atari-mint-ar
RM = rm -f

# Name der erzeugten Library-Datei
LIB_NAME = e_gem32.olb

# GCC Compiler Optionen: OHNE -mshort (int = 32 bit)
GCCOPTS = -O2 -fomit-frame-pointer

# GCC Compiler Optionen
CFLAGS = -Wall $(GCCOPTS) -D__CREATE_E_GEM_LIB__
OBJS = dial.o xacc_av.o objcedit.o objc.o popup.o graf.o tool.o \
       window.o event.o rc_ob_c.o fselect.o alerts.o dragdrop.o filetool.o

$(LIB_NAME): $(OBJS)
	$(AR) rc $(LIB_NAME) $(OBJS)

$(OBJS): e_gem.h proto.h

.PHONY:
	clean cleanall

CLEANFILES = $(OBJS) compile.err *~

CLEANALLFILES = $(CLEANFILES) $(LIB_NAME)

clean:
	$(RM) $(CLEANFILES)

cleanall:
	$(RM) $(CLEANALLFILES)
